version: "3.9"
services:
  api:
    build: .
    ports: ["8000:8000"]
    environment:
      - MIXER_DEFAULT_SPLIT=0.5
      - USE_FAISS=0
      - DATABASE_URL=sqlite+aiosqlite:///./data/qgi.db
      - JULIA_SERVER_URL=http://julia:8088
      - JULIA_WS_URL=ws://julia:8089
      - ALULS_PREFER_WS=1
      - ALULS_HTTP_TTL=30
      - ALULS_WS_TTL=30
      - NUMBSKULL_HTTP_URL=http://numbskull:9090
      - NUMBSKULL_WS_URL=ws://numbskull:9091
      - NUMBSKULL_PREFER_WS=1
      - NUMBSKULL_TTL=30
    depends_on:
      julia:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/"]
      interval: 15s
      timeout: 5s
      retries: 10
    volumes:
      - ./data:/app/data
      - ./src:/app/src
 cursor/bc-f408c7bd-bc2a-48a4-bc8d-0989f628ad52-ef2e



  julia:
    build:
      context: .
      dockerfile: julia_server/Dockerfile
    ports: ["8088:8088", "8089:8089"]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8088/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  numbskull:
    image: numbskull/tools:latest
    ports: ["9090:9090", "9091:9091"]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9090/health"]
      interval: 15s
      timeout: 5s
      retries: 10
